name: Marketplace Generator

on:
  # Run CI also on push to master
  push:
    branches:
      - development
      - master

jobs:
  build-marketplace:
    name: Build marketplace
    runs-on: ubuntu-latest

    steps:
      - name: Get branch name
        id: branch
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
      - name: Checkout current repo
        uses: actions/checkout@v2
        with:
          path: functions
      - name: Checkout Marketplace
        uses: actions/checkout@v2
        with:
          repository: mlrun/marketplace
          path: marketplace
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Requirements
        uses: py-actions/py-dependency-install@v2
        with:
          update-pip: "true"
          path: "functions/requirements.txt"
      - name: Build marketplace docs
        run: |
          python functions/functions.py build-docs -s ./functions -t ./marketplace -c ${{ steps.branch.outputs.branch }}
      - name: Publish marketplace release
        env:
          GITHUB_TOKEN: ${{ secrets.MARKETPLACE_ACCESS_TOKEN }}
        run: |
          cd marketplace

          COMMIT_SHA=$(git rev-parse --short "$GITHUB_SHA")
          BRANCH_NAME=marketplace-doc-gen-$COMMIT_SHA
          REMOTE=***github.com/$USERNAME/$REPO_PATH.git

          echo "Validating environment params...";

          [ -z "${GITHUB_TOKEN}" ] && {
              echo 'Missing input "GITHUB_TOKEN: ***".';
              exit 1;
          };

          git config --local user.name "github-worflow[bot]"

          echo "Checking out [$BRANCH_NAME]..."
          git checkout -b $BRANCH_NAME

          echo "Commiting changes..."
          git add -A && git commit -m "Automatically generated by github-worflow[bot] for commit: $COMMIT_SHA"

          echo "Pushing [$BRANCH_NAME] to remote [$REMOTE]"
          git push $REMOTE $BRANCH_NAME

          echo "Submiting pull request..."
          gh pr create --title "Marketplace update from $BRANCH_NAME" --body "github-workflow" --base $BASE_BRANCH --head $BRANCH_NAME --repo $USERNAME/$REPO_PATH
