name: Marketplace Generator

on:
  # Run CI also on push to master
  push:
    branches:
      - development
      - master

jobs:
  build-marketplace:
    name: Build marketplace
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch and timestamp
        shell: bash
        id: push_info
        run: |
          echo "##[set-output name=branch_name;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "##[set-output name=time_stamp;]$(echo ${GITHUB_REF#refs/heads/})"
      - name: Checkout current repo
        uses: actions/checkout@v2
        with:
          path: functions
      - name: Checkout Marketplace
        uses: actions/checkout@v2
        with:
          repository: mlrun/marketplace
          path: marketplace
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Requirements
        uses: py-actions/py-dependency-install@v2
        with:
          update-pip: "true"
          path: "functions/requirements.txt"
      - name: Build marketplace docs
        run: |
          python functions/functions.py build-docs -s ./functions -t ./marketplace -c ${{ steps.push_info.outputs.branch_name }}
      - name: Publish marketplace release
        env:
          GITHUB_TOKEN: ${{ secrets.MARKETPLACE_ACCESS_TOKEN }}
        run: |
          cd marketplace
          git config user.name "github-ci"
          branch='marketplace-doc-gen-${{ steps.push_info.outputs.branch_name }}-${{ steps.push_info.outputs.time_stamp }}'
          echo $branch
          git checkout -b $branch
          git add -A && git commit -m "Automated build"
          git push --set-upstream origin $branch