name: Marketplace Generator

on:
  push:
    branches:
      - development
      - master

jobs:
  build-marketplace:
    name: Build marketplace
    if: github.repository == 'mlrun/functions'
    runs-on: ubuntu-latest

    steps:
      - name: Get branch name
        id: branch
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
      - name: Checkout current repo
        uses: actions/checkout@v2
        with:
          path: functions
      - name: Checkout Marketplace
        uses: actions/checkout@v2
        with:
          repository: mlrun/marketplace
          path: marketplace
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Requirements
        uses: py-actions/py-dependency-install@v2
        with:
          update-pip: "true"
          path: "functions/requirements.txt"
      - name: Build marketplace docs
        env:
          CHANNEL: ${{ steps.branch.outputs.branch }}
        run: |
          python functions/functions.py build-docs -s ./functions -t ./marketplace -c $CHANNEL
      - name: Publish marketplace release
        env:
          GITHUB_TOKEN: ${{ secrets.MARKETPLACE_ACCESS_TOKEN_V2 }}
          USERNAME: Michaelliv
          REPO_PATH: marketplace
          BASE_REPO: mlrun
          BASE_BRANCH: master
        run: |
          cd marketplace

          COMMIT_SHA=$(git rev-parse --short "$GITHUB_SHA")
          BRANCH_NAME=marketplace-doc-gen-$COMMIT_SHA
          REMOTE=https://$USERNAME:$GITHUB_TOKEN@github.com/$BASE_REPO/$REPO_PATH.git

          echo "Validating environment params...";

          [ -z "${GITHUB_TOKEN}" ] && {
              echo 'Missing input "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}".';
              exit 1;
          };

          git config --local user.name $USERNAME

          echo "Checking out [$BRANCH_NAME]..."
          git checkout -b $BRANCH_NAME

          echo "Commiting changes..."
          git add -A && git commit -m "Automatically generated by github-worflow[bot] for commit: $COMMIT_SHA"

          # https://stackoverflow.com/questions/64270867/auth-error-trying-to-copy-a-repo-with-github-actions
          git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | xargs -L1 git config --unset-all

          echo "Pushing [$BRANCH_NAME] to remote [$REMOTE]"
          git push $REMOTE $BRANCH_NAME

          echo "Submiting pull request..."
          gh pr create --title "Marketplace update from $BRANCH_NAME" --body "github-workflow" --base $BASE_BRANCH --head $BRANCH_NAME --repo $BASE_REPO/$REPO_PATH