name: Marketplace Generator

on:
  # Run CI also on push to master
  push:
    branches:
      - development
      - master

jobs:
  build-marketplace:
    name: Build marketplace
    runs-on: ubuntu-latest

    steps:
      - name: Get branch name
        id: branch
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M')"
      - name: Checkout current repo
        uses: actions/checkout@v2
        with:
          path: functions
      - name: Checkout Marketplace
        uses: actions/checkout@v2
        with:
          repository: mlrun/marketplace
          path: marketplace
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Requirements
        uses: py-actions/py-dependency-install@v2
        with:
          update-pip: "true"
          path: "functions/requirements.txt"
      - name: Build marketplace docs
        run: |
          python functions/functions.py build-docs -s ./functions -t ./marketplace -c ${{ steps.branch.outputs.branch }}
      - name: Publish marketplace release
        env:
          GITHUB_TOKEN: ${{ secrets.MARKETPLACE_ACCESS_TOKEN }}
        run: |
          cd marketplace
          git config user.name "github-ci"
          branch='marketplace-doc-gen-${{ steps.branch.outputs.branch }}-${{ steps.date.outputs.date }}'
          echo $branch
          git checkout -b $branch
          git add -A && git commit -m "Automated build"
          git push --set-upstream origin $branch