name: CI

on:
  pull_request:
    branches:
      - "*"

      # Run CI also on push to master
  push:
    branches:
      - development
      - master

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      # Source
      - name: Checkout current repo
        uses: actions/checkout@v2
        with:
          path: functions
      # Install python
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      # Install dependencies
      - name: Install requirements.txt
        uses: py-actions/py-dependency-install@v2
        with:
          update-pip: "true"
          path: "functions/requirements.txt"
      # Run tests
      - name: Run python tests
        run: |
          python functions/functions.py test-suite -r ./functions -s items
          python functions/functions.py test-suite -r ./functions -s py
          python functions/functions.py test-suite -r ./functions -s ipynb
